# `DSML_WS_02` - Introduction to Python Library Management & `NumPy`

Please work on the following tasks **before** the second workshop session.

## 1. Programming a simple calculator in Python

Last week, you made yourself familiar with Python, getting to know about data structures like values, lists and dictionaries, explored for loops and if statements, and learned how to define functions. To put your knowledge of basic Python to the test, write a properly documented python function that can perform the taks of a simple calculator with the following behaviour:

1. The user shall pass the desired mathematical operation (plus, minus, divide, multiply) and two numbers

2. The result shall be calculated and printed

3. If the input for the mathematical operation is not covered by the list from above, print "Please correct your input"

**You should use the following elements:** 

- If/elif/else statement
- Functions
- Mathematical expressions

In [33]:

def simple_calc(first_num, ops, second_num):
    """
    Perform a mathematical operation between two numbers
    ...
    
    Arguments
    ---------
    first_num     : int/float
                    first number in calculation
                    
    ops           : str
                    mathematical operation; ops=["plus", "minus", "multiply", "divide"]
    
    second_num    : int/float
                    second number in calculation
    
    Returns
    -------
    result : str
            Operation and results of operation as string
    """
    #### your code below ####
    if(ops == "plus"):
        result = first_num + second_num
    elif(ops == "minus"):
        result = first_num - second_num
    elif(ops == "multiply"):
        result = first_num * second_num
    elif(ops == "divide"):
        if(second_num == 0):
            return "why did you divide by 0?"
        result = first_num/second_num
    else:
        return "Please correct your imput"

    returnString = "The result is: " + str(result)
    return returnString


In [34]:
# try out your calculator by calling the simple_calc function with different argument values
print(simple_calc(2,"divide",0))

why did you divide by 0?


## 2. Getting started with NumPy

This week, we will be exploring our first Python package, namely NumPy. Get prepared for the workshop by completing the below steps:

In order to use NumPy's capabilities, we first have to import it. Do this by running the following cell. We use the `as` keyword so we can use an abbreviation when calling NumPy methods.

In [36]:
import numpy as np

The core structure of NumPy is the N-dimensional array object. You can create arrays using `np.array([..,..,..])`. Do the following:
1. Create a list of 5 integers and assign it to a variable called `lst`.
2. Use `lst` to create a NumPy array, and assign this array to a variable called `my_first_array`.
3. Verify that the type of `my_first_array` is np.array.
4. Create a second array, consisting of the first 3 numbers from `my_first_array`, and assign it to a variable called `my_second_array` (tip: selecting a subset of elements from arrays works similarly to lists).
5. Create a third array, which contains each number from `my_second_array` multiplied by 3, and assign it to a variable called `my_third_array` (tip: thinking about list operations from last week will help you here once again).

In [39]:
# your code here
lst = [6,7,2,3,4]
my_first_array = np.array(lst)

if isinstance(my_first_array, np.ndarray):
    print("my_array is a numpy array")
else:
    print("my_array is not a numpy array")

my_second_array = np.array(my_first_array[0:3])
my_third_array = my_second_array*3

print(my_second_array.tolist())
print(my_third_array.tolist())


my_array is a numpy array
[6, 7, 2]
[18 21  6]


Finally, let's combine `my_second_array` and `my_third_array`. We can use the functions np.hstack((`first_array`,`second_array`)) or np.vstack((`first_array`,`second_array`)) for this. Combine `my_second_array` and `my_third_array` using both functions. How does the output differ? Can I also use both functions to combine `my_first_array`and `my_second_array`?

In [40]:
# your code here
my_hcombined_array = np.hstack((my_second_array,my_third_array))
my_vcombined_array = np.vstack((my_second_array,my_third_array))

print(my_hcombined_array)
print(my_vcombined_array)


[ 6  7  2 18 21  6]
[[ 6  7  2]
 [18 21  6]]
