# `DSML_WS_03` - Introduction to Pandas

In this tutorial we will continue with our introduction series to key python data science libraries. Today we will focus on `Pandas`.

We will go through the following:

- **Task**: Working with student grades in NumPy
- **Task**: Getting started with Pandas
- **Introduction to `Pandas` objects**: Learn what `Pandas` Series, DataFrames and Indices are and what they are used for
- **Data selection in `Pandas`**: Index rows, columns and individual items in a `Pandas` Series and DataFrame
- **Data analysis and manipulation in `Pandas`**: Perform advanced hierarchical indexing on your dataset, run simple descriptives on your dataset, basic handling of missing data, carry out aggregation and grouping

---

## 1. Task: Working with student grades in NumPy

Last week, you made yourself familiar with NumPy. Let's check your NumPy knowledge using a small case.

Imagine you are the teacher of a class of 15 students. During the year, the class has written 3 tests, each with a maximum of 100 points. You want to summarize the students' performances using NumPy.

1. Simulate the described case by creating a two-dimensional NumPy array with each row representing a student and each column representing a test. Generate random scores for each student and test between 0 and 100, and assign the array to a variable called `student_scores`.
2. Oops! You completely forgot Thomas, who joined the class during the school year after the first test. Thomas' score for the second test was 87, and 93 for the third test.
    - Since Thomas does not have a score for the first test, you want to simply use the average score of all other students. Calculate this and assign it to a variable called `avg_first_test`. (Hint: array slicing and the function np.mean() might be helpful here)
    - Add Thomas using `avg_first_test` as his first test score and his actual second and third test scores to `student_scores`.
3. You want to generate the sum of the scores from all three tests for each student. Do this using a matrix multiplication and save the resulting array to a variable called `student_totals`.
4. Finally, you want to transform the total scores in `student_totals` to a percentage of maximum available points. Assign this array to a variable called `student_pct`.

In [1]:
import numpy as np

In [2]:
student_scores = np.random.randint(low=0,high=101, size=(15,3))
student_scores

array([[24, 28,  7],
       [43, 24, 40],
       [43, 46, 86],
       [14, 81, 53],
       [ 5, 56, 90],
       [57, 50, 11],
       [29, 95, 57],
       [35,  2, 35],
       [45, 56, 48],
       [22, 96, 10],
       [95, 56, 80],
       [94, 56, 81],
       [56, 37, 91],
       [90, 52, 15],
       [23, 44, 59]])

In [3]:
avg_first_test = np.mean(student_scores[:,0])
avg_first_test

45.0

In [4]:
thomas_scores = np.array([avg_first_test, 87, 93])
student_scores = np.vstack((student_scores,thomas_scores))
student_scores

array([[24., 28.,  7.],
       [43., 24., 40.],
       [43., 46., 86.],
       [14., 81., 53.],
       [ 5., 56., 90.],
       [57., 50., 11.],
       [29., 95., 57.],
       [35.,  2., 35.],
       [45., 56., 48.],
       [22., 96., 10.],
       [95., 56., 80.],
       [94., 56., 81.],
       [56., 37., 91.],
       [90., 52., 15.],
       [23., 44., 59.],
       [45., 87., 93.]])

In [5]:
student_totals = student_scores@np.ones((3,1))
student_totals

array([[ 59.],
       [107.],
       [175.],
       [148.],
       [151.],
       [118.],
       [181.],
       [ 72.],
       [149.],
       [128.],
       [231.],
       [231.],
       [184.],
       [157.],
       [126.],
       [225.]])

In [6]:
student_pct = student_totals / 300
student_pct

array([[0.19666667],
       [0.35666667],
       [0.58333333],
       [0.49333333],
       [0.50333333],
       [0.39333333],
       [0.60333333],
       [0.24      ],
       [0.49666667],
       [0.42666667],
       [0.77      ],
       [0.77      ],
       [0.61333333],
       [0.52333333],
       [0.42      ],
       [0.75      ]])

---

## 2. Task: Getting started with Pandas

This week, we will be exploring Pandas - a core package for working with data in Python. You can think of Pandas as enhanced versions of NumPy arrays. Let's see why.

As always, we first have to import pandas to use its functionalities within this Jupyter notebook. Pandas is commonly abbreviated using pd.

In [7]:
import pandas as pd

The Pandas equivalent to a one-dimensional array is a Series object, which you can create just like arrays, but use pd.Series instead of np.array. Let's stick with the student grade example from Task 1, but focus on only five students: Helena, Tom, Nina, Sam and Kim, who are 15, 15, 16, 17 and 16 years old, and scored 75, 69, 87, 88, and 54 points on the first test. Create three Pandas Series objects called `names`, `ages` and `scores` to store the respective data about our five students. How do Pandas Series objects differ from NumPy arrays?

In [8]:
names = pd.Series(["Helena", "Tom", "Nina", "Sam", "Kim"])
ages = pd.Series([15, 15, 16, 17, 16])
scores = pd.Series([75, 69, 87, 88, 54])
names

0    Helena
1       Tom
2      Nina
3       Sam
4       Kim
dtype: object

At the heart of Pandas are dataframes, the equivalent to two-dimensional arrays. Let's combine our three Series objects into one dataframe using pd.DataFrame({'name_1': series_1, 'name_2': series_2,...}) and assign it to a variable called `students`. How does the dataframe differ from a two-dimensional array?

In [9]:
students = pd.DataFrame({'name': names, 'age': ages, 'score': scores})
students

name  age  score
0  Helena   15     75
1     Tom   15     69
2    Nina   16     87
3     Sam   17     88
4     Kim   16     54

You can select specific information from your dataframe using the .loc[row_name, column_name] method. Return all rows but only the age column using .loc.

In [10]:
students.loc[:,'age']

0    15
1    15
2    16
3    17
4    16
Name: age, dtype: int64

We can also use .loc to filter based on certain conditions. For example, if I want to only return Helena's test score, I could write `students.loc[students.name == 'Helena','score']`. Return all information on students with a score higher than 80.

In [11]:
students.loc[students.name == 'Helena','score']

0    75
Name: score, dtype: int64

In [12]:
students.loc[students.score > 80,:]

name  age  score
2  Nina   16     87
3   Sam   17     88

---

## 3. Introduction to `Pandas` objects

Pandas is a newer package built on top of `NumPy`, and provides an efficient implementation of a `DataFrame`, the core Pandas object. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data. As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs. We will use `Pandas` as the main tool to structure, manipulate and store data throughout this course. As such, Pandas constitutes a core data science library that all of you should be very well familiar with.

Let's get started...

In [13]:
# import pandas if not done above
import pandas as pd

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices. Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are. Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the Series, DataFrame, and Index.



#### The `Pandas Series` Object
A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [14]:
# create a Series using pd.Series and assign it to variable A
A = pd.Series([12,13,14,15,16,17])
A

0    12
1    13
2    14
3    15
4    16
5    17
dtype: int64

In [15]:
# return the type of the created Series
type(A)

pandas.core.series.Series

As we see in the output, the Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes. The values are simply a familiar NumPy array:

In [16]:
# return the values of A using A.values
A.values

array([12, 13, 14, 15, 16, 17])

The index is an array-like object of type pd.Index, which we'll discuss in more detail later.

In [17]:
# return the indices of A using A.index
A.index

RangeIndex(start=0, stop=6, step=1)

From what we've seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. **The essential difference is the presence of the index**: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.
This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. For example, if we wish, we can use strings as an index:


In [18]:
# create a Series B and assign strings as index using the "index=[]"
B = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
B

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In this way, you can think of a Pandas Series a bit like a **specialization of a Python dictionary**. A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure which maps typed keys to a set of typed values. This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas Series makes it much more efficient than Python dictionaries for certain operations.
The Series-as-dictionary analogy can be made even more clear by constructing a Series object directly from a Python dictionary:

In [19]:
# note the following dictionary of state populations
population_dict = {'California': 38332521,
                   'Texas': 2644819,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population_dict

{'California': 38332521,
 'Texas': 2644819,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [20]:
# create a Series from population_dict
population_series = pd.Series(population_dict)
population_series

California    38332521
Texas          2644819
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Unlike a dictionary, though, the Series also supports array-style operations such as slicing:

In [21]:
# returning a single element works both with dictionaries and Series
print(population_dict["California"])
print(population_series["California"])

38332521
38332521


In [22]:
# try to return the first three populations (California, Texas, New York) from population_dict
population_dict["California":"New York"]

KeyError: slice('California', 'New York', None)

In [23]:
# try to return the first three populations (California, Texas, New York) from population_series
population_series["California":"New York"]

California    38332521
Texas          2644819
New York      19651127
dtype: int64

#### The `Pandas DataFrame` Object
The next fundamental structure in `Pandas`  is the `DataFrame` . Like the Series object discussed in the previous section, the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary. We'll now take a look at each of these perspectives.

If a Series is analogous to a one-dimensional array with flexible indices, a DataFrame is analogous to a two-dimensional array with both flexible row indices and flexible column names. Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects. Here, by "aligned" we mean that they share the same index.

In [24]:
# let's create a second series of state areas
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area_series = pd.Series(area_dict)
area_series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [25]:
# create a Pandas Dataframe called states using pd.DataFrame
states = pd.DataFrame({'population': population_series,
                       'area': area_series})
states

population    area
California    38332521  423967
Texas          2644819  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [26]:
# return the type of states
type(states)

pandas.core.frame.DataFrame

In [27]:
# return the values of states 
states.values

array([[38332521,   423967],
       [ 2644819,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

Like the Series object, the DataFrame has an index attribute that gives access to the index labels:

In [28]:
# return the indices of states
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels:

In [29]:
# return the column names of states using .columns
states.columns

Index(['population', 'area'], dtype='object')


Thus the DataFrame can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

### The `Pandas Index` Object
We have seen here that both the Series and DataFrame objects contain an explicit index that lets you reference and modify data. This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multi-set, as Index objects may contain repeated values). Those views have some interesting consequences in the operations available on Index objects. As a simple example, let's construct an Index from a list of integers:

In [30]:
# create an Index object ind using pd.Index
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

The Index in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices:

In [31]:
# return the first element of ind
ind[0]

2

In [32]:
# return every second object of ind
ind[::2]

Index([2, 5, 11], dtype='int64')

Index objects also have many of the attributes familiar from NumPy arrays:

In [33]:
# print the size, shape, number of dimensions and data type of ind
print(
    "Size:", ind.size,
    "\nShape:", ind.shape, 
    "\nNumber of dimensions:", ind.ndim, 
    "\nDatatype:", ind.dtype)

Size: 5 
Shape: (5,) 
Number of dimensions: 1 
Datatype: int64


One difference between Index objects and NumPy arrays is that indices are immutable – that is, they cannot be modified via the normal means

In [34]:
# try to change the value of the first element of ind
ind[0] = 5

TypeError: Index does not support mutable operations

---

## 4. Extracting values in `Pandas`

The terminology used below (e.g. extracting, selecting, slicing...) can be confusing sometimes. For a quick overview, refer to https://avichawla.substack.com/p/are-you-sure-you-are-using-the-correct for a nice, intuitive overview.

#### Extracting values from a Series

As we saw in the previous section, a Series object acts in many ways like a one-dimensional NumPy array, and in many ways like a standard Python dictionary. If we keep these two overlapping analogies in mind, it will help us to understand the patterns of data indexing and extraction in these arrays.

Like a dictionary, the Series object provides a mapping from a collection of keys (i.e. the index) to a collection of values:

In [35]:
# remember our Series B
B

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [36]:
# return the first element of B using an explicit index (as we are used to from Python dictionaries)
B["a"]

0.25

We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [37]:
# use the .keys() method to extract the indices of B
B.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
# use the .items() method to extract keys,value pairs
list(B.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Series objects can even be modified with a dictionary-like syntax. Just as you can extend a dictionary by assigning to a new key, you can extend a Series by assigning to a new index value:


In [39]:
# add a new key,value pair to B
B['x'] = 100
B

a      0.25
b      0.50
c      0.75
d      1.00
x    100.00
dtype: float64

In [40]:
# change the value of the first element of B
B['a'] = 0
B

a      0.00
b      0.50
c      0.75
d      1.00
x    100.00
dtype: float64

A Series builds on this dictionary-like interface and provides array-style item extraction via the same basic mechanisms as NumPy arrays. Examples of these are as follows:

In [ ]:
# slicing by explicit index: extract the first three elements of B
B['a':'c']

In [ ]:
# slicing by implicit index: extract the first three elements of B
B[0:3]

In [ ]:
# multiple explicit indexing: extract multiple elements using a list of indices
B[["a", "c", "x"]]

Notice that when slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice.

**Indexers: loc and iloc**

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as B[1] will use the explicit indices, while a slicing operation like B[1:3] will use the implicit Python-style index.

In [ ]:
# let's create a new Series with explicit integer indices
C = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
C

In [ ]:
# explicit index when extracting a single row
C[1]

In [ ]:
# implicit index when slicing multiple rows
C[1:3]

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.
First, the `.loc` attribute allows indexing and slicing that always references the **explicit index**:

In [ ]:
# extract the value "a" using .loc[]
C.loc[1]

In [ ]:
# extract the values "a" and "b" using .loc[]
C.loc[1:3]

The `.iloc` attribute allows indexing and slicing that always references the **implicit Python-style index**:

In [ ]:
# extract the value "a" using .iloc[]
C.iloc[0]

In [ ]:
# extract the values "a" and "b" using .iloc[]
C.iloc[0:2]

One guiding principle of Python code is that **"explicit is better than implicit"**. The explicit nature of `.loc` and `.iloc` make them very useful in maintaining clean and readable code; especially in the case of integer indices, I recommend using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

#### Extracting data from a DataFrame

Recall that a DataFrame acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of Series structures sharing the same index. These analogies can be helpful to keep in mind as we explore data extraction within this structure.

In [ ]:
# remember our states DataFrame
states

The individual Series that make up the columns of the DataFrame can be selected via dictionary-style indexing of the column name:

In [ ]:
# select the area column of states
states["area"]

In [ ]:
# alternatively, you can also select a column by appending its name to the name of the DataFrame
states.area

In [41]:
# return the values of the area column
states["area"].values

array([423967, 695662, 141297, 170312, 149995])

Like with the Series objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [42]:
# let's add the population density to states
states["pop_density"] = states["population"] / states["area"]
states

population    area  pop_density
California    38332521  423967    90.413926
Texas          2644819  695662     3.801874
New York      19651127  141297   139.076746
Florida       19552860  170312   114.806121
Illinois      12882135  149995    85.883763

In [43]:
# select the pop_density column from states
states["pop_density"]

California     90.413926
Texas           3.801874
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: pop_density, dtype: float64

As mentioned previously, we can also view the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute:

In [44]:
# return the data of states using .values
states.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481900e+06, 6.95662000e+05, 3.80187361e+00],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

With this picture in mind, many familiar array-like operations can be done on the DataFrame itself. For example, we can transpose the full DataFrame to swap rows and columns:

In [45]:
# transpose states using .T
states.T

California         Texas      New York       Florida  \
population   3.833252e+07  2.644819e+06  1.965113e+07  1.955286e+07   
area         4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
pop_density  9.041393e+01  3.801874e+00  1.390767e+02  1.148061e+02   

                 Illinois  
population   1.288214e+07  
area         1.499950e+05  
pop_density  8.588376e+01

When it comes to indexing of DataFrame objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row:

In [46]:
# returns a row
states.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

...and passing a single "index" to a DataFrame accesses a column:

In [47]:
# returns a column
states["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

The difference between NumPy arrays and DataFrames becomes evident also when attempting to access a single element. While you might remember from last week's workshop that we can access an element in a two-dimensional array as follows:

In [48]:
# returns the element in the first row and second column
states.values[0,1]

423967.0

...the same does not work for our DataFrame:

In [49]:
# results in an error message
states[0,1]

KeyError: (0, 1)

Thus for array-style indexing, we need another convention. Here Pandas again uses the `.loc` and `.iloc` indexers mentioned earlier. Using the `.iloc` indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [50]:
states

population    area  pop_density
California    38332521  423967    90.413926
Texas          2644819  695662     3.801874
New York      19651127  141297   139.076746
Florida       19552860  170312   114.806121
Illinois      12882135  149995    85.883763

In [51]:
# return the first three rows and first two columns of states using iloc (implicit indices)
states.iloc[:3, :2]

population    area
California    38332521  423967
Texas          2644819  695662
New York      19651127  141297

Similarly, using the `.loc` indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [52]:
# return the first three rows and first two columns of states using loc (explicit indices)
states.loc[:"New York", :"area"]

population    area
California    38332521  423967
Texas          2644819  695662
New York      19651127  141297

We can also pass conditions to the indexer, a technique called **masking**.

In [53]:
# masking with .loc: return the states with pop_density > 100
states.loc[states.pop_density > 100,:]

population    area  pop_density
New York    19651127  141297   139.076746
Florida     19552860  170312   114.806121

In [54]:
# multiple conditions
states.loc[(states.pop_density > 100) & (states.area > 150000),:]

population    area  pop_density
Florida    19552860  170312   114.806121

Even though we prefer using indexers like .loc, a commonly used way to implement boolean masking is shown below.

In [55]:
# masking with explicit column index
mid_sized_states_df = states[(states["population"] > 15000000) & (states["population"] < 30000000)]
mid_sized_states_df

population    area  pop_density
New York    19651127  141297   139.076746
Florida     19552860  170312   114.806121

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [56]:
# change the population density of California to 100
states.loc["California","pop_density"] = 100
states

population    area  pop_density
California    38332521  423967   100.000000
Texas          2644819  695662     3.801874
New York      19651127  141297   139.076746
Florida       19552860  170312   114.806121
Illinois      12882135  149995    85.883763

Look at the following line of code, where we try to add a column to our mid_sized_states_df:

In [57]:
mid_sized_states_df["area_x10"] = mid_sized_states_df["area"]*10

/var/folders/4_/t2157_4x5pg6g2g8m0k859fw0000gn/T/ipykernel_59822/4108304400.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mid_sized_states_df["area_x10"] = mid_sized_states_df["area"]*10


The above warning is something you will encounter when working with pandas Dataframes. It is intended to give you a warning that the behavior that you will get executing this code is not always what you expect. It comes from the definition of mid_sized_states_df.

Pandas is unsure whether you wanted to add values to the 'states' dataframe or the 'mid_sized_states_df' dataframe!
To get rid of this error, you can explicitly copy the dataframe so pandas knows we are trying to add a column to the 'new' dataframe 'mid_sized_states_df'.

In [58]:
mid_sized_states_df = states[(states["population"] > 15000000) & (states["population"] < 30000000)].copy()
mid_sized_states_df["area_x10"] = mid_sized_states_df["area"]*10

In [59]:
mid_sized_states_df

population    area  pop_density  area_x10
New York    19651127  141297   139.076746   1412970
Florida     19552860  170312   114.806121   1703120

---

## 5. Data analysis and manipulation in `Pandas`

#### Hierarchical Indexing

**Using MultiIndex to create hierarchical DataFrames**

Often it is useful to store higher-dimensional data, i.e. data indexed by more than one or two keys. The most appropriate Pandas function for this is `MultiIndex`. We will demonstrate using a simple example:

In [60]:
# We use a 2-D example, first specifying the outer and inner dimension as well as the values
Outer = ['California','California',
         'New York','New York',
         'Texas','Texas']

Inner = [2000,2010,
         2000,2010,
         2000,2010]

populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

# From the outer and inner dimensions we create an index

index_list = list(zip(Outer,Inner))
index_list

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [61]:
# from index_list we can create a multi index
index_object = pd.MultiIndex.from_tuples(index_list)
index_object

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [62]:
# finally, we create a data frame with hierarchichal indices
df = pd.DataFrame(index=index_object,
                  data=populations,
                  columns=["Population"])

df

Population
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [63]:
# let's add more columns to df
area = [164,164, #California 
        55,55,   #NY State
        269,269] #Texas

df["Area"] = area
df["Density"] = df["Population"]/df["Area"]
df

Population  Area        Density
California 2000    33871648   164  206534.439024
           2010    37253956   164  227158.268293
New York   2000    18976457    55  345026.490909
           2010    19378102    55  352329.127273
Texas      2000    20851820   269   77516.059480
           2010    25145561   269   93477.921933

In [64]:
# again, we can easily transpose this DataFrame
df.transpose() # same as .T

California                    New York                \
                    2000          2010          2000          2010   
Population  3.387165e+07  3.725396e+07  1.897646e+07  1.937810e+07   
Area        1.640000e+02  1.640000e+02  5.500000e+01  5.500000e+01   
Density     2.065344e+05  2.271583e+05  3.450265e+05  3.523291e+05   

                   Texas                
                    2000          2010  
Population  2.085182e+07  2.514556e+07  
Area        2.690000e+02  2.690000e+02  
Density     7.751606e+04  9.347792e+04

**MultiIndex as an extra dimension**

The `unstack()` method let's us convert a hierachically indexed Series into a conventionally indexed DataFrame.

In [65]:
df['Population']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
Name: Population, dtype: int64

In [66]:
df['Population'].unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

#### Quick data analysis in `Pandas`

In practice your dataset will often be considerably larger than the illustrative example above. In these cases it is often useful to run brief descriptive statistical analyses on the set, which will help to get a first feel for the data. 

We will demonstrate how to do this using the provided `iris.csv` dataset. This is a famous dataset used frequently for educational purposes in data science. You can read up on the dataset, its content and its origins here: https://en.wikipedia.org/wiki/Iris_flower_data_set.

The iris dataset contains measurements for 150 iris flowers from three different species.

The __three classes__ in the Iris dataset:
* Iris-setosa (n=50)
* Iris-versicolor (n=50)
* Iris-virginica (n=50)

The __four features__ of the Iris dataset:
* sepal length in cm
* sepal width in cm
* petal length in cm
* petal width in cm

![Iris dataset explained (Source: apsl.net)](iris.original.png)

In [67]:
# first read in the dataset as a DataFrame
# for the indirect reference "iris.csv" to work make sure it is contained in the same folder as your notebook
# You can set the index by using the index_col function
iris_set = pd.read_csv("iris.csv", sep=",", index_col="number")

In [68]:
# examine the first 5 rows using .head()
iris_set.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
number                                                              
1                5.1          3.5           1.4          0.2  setosa
2                4.9          3.0           1.4          0.2  setosa
3                4.7          3.2           1.3          0.2  setosa
4                4.6          3.1           1.5          0.2  setosa
5                5.0          3.6           1.4          0.2  setosa

In [69]:
# return all column names using .columns
iris_set.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [70]:
# the .describe()-function provides an overview of key descriptive statistics
iris_set.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    148.000000   149.000000    149.000000   150.000000
mean       5.827703     3.055705      3.753020     1.199333
std        0.818479     0.436878      1.770195     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.300000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [71]:
# the .info()-function provides an overview of null values and datatypes per column
iris_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  148 non-null    float64
 1   Sepal.Width   149 non-null    float64
 2   Petal.Length  149 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [72]:
# you can also focus your analysis on individual features by indexing them
iris_set["Sepal.Width"].describe()

count    149.000000
mean       3.055705
std        0.436878
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: Sepal.Width, dtype: float64

In [73]:
# additionally you can call the functions seperately, e.g. .count()
iris_set.count()

Sepal.Length    148
Sepal.Width     149
Petal.Length    149
Petal.Width     150
Species         150
dtype: int64

#### Handling missing numerical data (`NaN` values)
If you have paid attention to the descriptive statistics above you will have noticed that the __count__ of values differs across features. This is a first indication for missing numerical data. In the real world you will often encounter incomplete and noisy data which will require pre-processing before you can apply data science and machine learning tools to them. In this section we will provide a quick overview on how to deal with missing data in your data sets. 
Note that Python has two ways of highlighting missing data:
* `NaN` - (acronym for Not a Number), is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation
* `None` - Python-specific object that is often used for missing data in Python code. Because it is a Python object, `None` can only be used in arrays with data type 'object' (i.e., arrays of Python objects) 

**Detecting missing numerical data**

Pandas data structures have two useful methods for detecting null data: `isnull()` and `notnull()`. Either one will return a Boolean mask over the data.

In [74]:
# .isnull() returns "True" for every missing numerical value in the dataset
iris_set.isnull()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
number                                                               
1              False        False         False        False    False
2              False        False         False        False    False
3              False        False         False        False    False
4              False        False         False        False    False
5              False        False         False        False    False
...              ...          ...           ...          ...      ...
146            False        False         False        False    False
147            False        False         False        False    False
148            False        False         False        False    False
149            False        False         False        False    False
150            False        False         False        False    False

[150 rows x 5 columns]

In [75]:
# .notnull() returns "False" for every missing numerical value in the dataset
iris_set.notnull()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
number                                                               
1               True         True          True         True     True
2               True         True          True         True     True
3               True         True          True         True     True
4               True         True          True         True     True
5               True         True          True         True     True
...              ...          ...           ...          ...      ...
146             True         True          True         True     True
147             True         True          True         True     True
148             True         True          True         True     True
149             True         True          True         True     True
150             True         True          True         True     True

[150 rows x 5 columns]

In [ ]:
# we can also use masking to display rows with null values in a specific column
iris_set[iris_set["Sepal.Width"].isnull() == True]

In [76]:
# we can also use masking to display rows with null values in any column
iris_set[iris_set.isnull().any(axis=1) == True]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
number                                                                  
24               5.1          NaN           1.7          0.5      setosa
79               6.0          2.9           NaN          1.5  versicolor
123              NaN          2.8           6.7          2.0   virginica
124              NaN          2.7           4.9          1.8   virginica

In essence two approaches to dealing with missing data exist:
* __Elimination__: Dropping null values from the dataset
* __Imputation__: Imputing/replacing null values with numerical values/estimates

**Elimination (i.e. dropping null values)**

We cannot drop single values from a data frame; we can only drop full rows or full columns. Depending on the application, you might want one or the other, so `dropna()` gives a number of options:

We use the `dropna(axis=0)` function to drop all rows from the dataset that include null values. Note that `dropna()` will not modify your dataframe unless you call `dropna(axis=0,inplace=True)`.

In [ ]:
# let's drop all rows that include null values but not modify the dataframe
iris_set.dropna(axis=0, inplace=False)

We use the `dropna(axis=1)` function to drop all columns from the dataset that incl. null values. Note that, also in this case, `dropna()` will not modify your dataframe unless you call `dropna(axis=1,inplace=True)`

In [ ]:
# let's drop all columns that include null values but not modify the dataframe
iris_set.dropna(axis=1, inplace=False)

In [ ]:
# note that our dataframe has not been modified, i.e. we still have all 150 rows and 5 columns
iris_set.shape

In [ ]:
# we can therefore also use dropna() to easily identify the number of rows with missing values 
len(iris_set)-len(iris_set.dropna())

In [ ]:
# if you wish to clean the data with dropna, it is good practice to define a new data frame (instead of using inplace=True)
iris_set_clean = iris_set.dropna(axis=0).copy()

In [ ]:
# compare the number of rows of our original and clean dataframes
print("iris_set:",len(iris_set))
print("iris_set_clean:",len(iris_set_clean))

**Imputation (i.e. filling null values)**

Imputation fills null values with numerical values chosen by the data scientist. For this, `fillna()`provides the appropriate tools.

The data scientist will usually choose one of the following methods:
* Fill with zeros: `fillna(0)`
* Conduct a forward fill (i.e. filling NaN values with data from previous observation): `fillna(method="ffill")`
* Conduct a backward fill (i.e. filling NaN values with data from following observation): `fillna(method="bfill")`
* Fill with the column mean,max,min, etc.: `df["Col_name"].fillna(value=df["Col_name"].mean())`
* Custom fill depending on the application

In [ ]:
# let's replace the NaN values in Sepal.Length with the average sepal length
iris_set["Sepal.Length"] = iris_set["Sepal.Length"].fillna(value=iris_set["Sepal.Length"].mean())

In [ ]:
# check out the new values of the 123rd and 124th flower for Sepal.Length
iris_set.loc[120:125,:]

#### Data aggregation and grouping
The `groupby()` method allows for grouping of rows and the application of aggregation functions to these grouped rows. It is a highly useful method in data science and used extensively. We will return to the iris dataset for illustration purposes.

In [ ]:
# let's get some summary statistics for the different species (setosa, versicolor, virginica), e.g. the mean of our four features
species_groups_mean = iris_set.groupby("Species").mean()
species_groups_mean

In [ ]:
# you can also use other aggregation routines, including .sum(), .max(), .min(), .count()
species_groups_min = iris_set.groupby("Species").min()
species_groups_min

In [ ]:
# we can also apply multiple aggregation routines at the same time using .agg()
species_groups_agg = iris_set.groupby("Species").agg(['mean', 'max', 'count'])
species_groups_agg

Finally you can also profide custom aggregation routines, which is useful if features follow different aggregation routines. As an illustrative (albeit not very realistic example) we will implement the following aggregation rules:

- Sepal.Length: `max()`
- Sepal.Width: `mean()`
- Petal.Length: `min()`
- Petal.Width: `mean()`

Custom aggregation is, again, implemented using the `.agg()` command.

In [ ]:
# first, define a dictionary that maps features to aggreagation routines
agg_dict = {'Sepal.Length':'max', 'Sepal.Width':'mean', 'Petal.Length':'min', 'Petal.Width':'mean'}

In [ ]:
# second, pass the dictionary as an argument to .agg()
species_groups_custom = iris_set.groupby("Species").agg(agg_dict)

In [ ]:
species_groups_custom

---